### ISSUE TITLE
 java.lang.NoSuchMethodError: No virtual method getByte(J)B in class Lsun/misc/Unsafe; or its super classes (declaration of 'sun.misc.Unsafe' appears in /system/framework/core-libart.jar)

### ISSUE THREAD

**Issue by lucgu** [iamironz/unsafe#2]
java.lang.NoSuchMethodError: No virtual method getByte(J)B in class Lsun/misc/Unsafe; or its super classes (declaration of 'sun.misc.Unsafe' appears in /system/framework/core-libart.jar)

i got that error when trying to get value from spesific memory address using getByte() method. Please help

**Comment by iamironz** [comment]
Hi @lucgu !

Can you please send me target device model and api level (also as many as possible software and hardware information include processor architecture) which throws this kind of exception?

Cheers.

**Comment by TaylorDale** [comment]
Getting the same error for copyMemory(), Target device is a Galaxy Note 4 on API 23.

**Comment by iamironz** [comment]
@Talerr right because this method has been introduced from 24 api and above. You can see specific javadoc mark and target api annotations.

**Comment by TaylorDale** [comment]
Yeah I did see that - is that a limitation of this abstraction layer somehow though? A memcpy-like function only being introduced in Android 7 seems to be strange, being so elementary? 

Regardless, thanks heaps for this adaptation I very much needed it.

**Comment by iamironz** [comment]
@Talerr this is because runtime limitations. After 21 api Android starts with part of `ojluni` runtime part (openjdk lang-util-net-io) which have some extra internal methods. 
Earlier api versions just works with another memory intrinsics and this versions have not full Unsafe api than 21 and upper. 
Yes, memcpy is simple but `sun.misc.Unsafe` is fully internal implementation for runtime specific proposes and not targeted for daily usages and some parts inside earlier Android runtimes has been implemented different.

**Comment by iamironz** [comment]
@lucgu bump
